name: fds.py
plugins:
  - name: solidity
  - name: alchemy
  - name: foundry
  - name: infura
  - name: etherscan
# ethereum:
#   default_network: mainnet-fork
#   mainnet_fork:
#     default_provider: foundry
#     gas_limit: auto
#     transaction_acceptance_timeout: 180 # 3 Minutes
#   mainnet:
#     transaction_acceptance_timeout: 180

# solidity:
#   version: 0.5.0
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10