name: fds.py
plugins:
  - name: solidity
  - name: alchemy
  - name: foundry
  - name: infura
  - name: etherscan
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
    gas_limit: auto
    transaction_acceptance_timeout: 180 # 3 Minutes
  mainnet:
    transaction_acceptance_timeout: 180