from pathlib import Path
from typing import Dict, List, Optional, Union

from ape.types import ABI

AbiType = Optional[Union[List[ABI], Dict, str, Path]]
# * vrs (tuple(v, r, s), each element is hex str, bytes or int) – the three
# * pieces generated by an elliptic curve signature
# * https://eth-account.readthedocs.io/en/stable/eth_account.html\
# * eth_account.account.Account.recover_message
VRS = Union[str, bytes, int]
